language: node_js
node_js:
- 11.1
- 10.15
- 8.9
git:
  depth: 3
script:
- npm run test
- npm run test:integration
after_success:
- npm run coverage
env:
  global:
  - secure: bHeanMiKVZB33yLIYKEDYeFTKThsVt0lCfCuWE69ZMWJV2kvy1GlrLhhTF/7bWqz3ygOGqmX5r51Ied2cOdc8NdLO4sWu/l+LTJF9P+2GhQfDHFCfLRHNHdsAbn/7gXsNSormy8zq9Zi8b+LCEfer3+JsIC4Vg4LHYNZj+QGF5pCj62sfBBHeLMZ0vGo294ug0n695dMCVRQNtd9B2jFtCayBbVBvlDvm1T1JxEssE0M4hAuzDBoP0OE/w/vXDKHOa1HiD0XSVLEdrEDQMv5wC7OiWMPChMYL0Hw25XanlxStDdPHrX8GRFMbfe/14aXRLVPTF0azLkkoLruOZ+LHWt2o7TBnuEGtQJEBFKbkCFe3w/E/SKCK/G867LjMld0ir6CNXME/gCIMB4I42tU4GkmL1wTEkFjlpYgPZFQBz4k7jEE0Ja50Grg4kXv91hPtBw5ottlI9Xr4yqSzE5int2RW2FRehaoAHleXZqIubxaW6P7rfc6n2zZuxCHSG7ptE8Ps7SZ2D+RbN7iIm7mmHjiwlmWUvvb7+rKMa6bwBo2nBksWuDiOinSl9gg+HKR+hPMDMNtK4PUJHihJta/KbK3qsHpuBfS00JkfDnD7aa4LycP29cjahsrHlbYk/pk4QUIfw7+QtPVeLzT6pfQeB1g/7CgO2v6oGWTcPFefcA=
  - secure: FMnfiCN3Mppc6CFqm7ru/hIS6EKHfzK1PsoYjXlRrSkFDFQuoDvYoUpLtF1BLdkwSHK29vCaHUvoIwLtsvQNksa5b1azF0vJdjkHKKoQEYTC4DvEkDK8TfDAuAUxOcwo4Gg0vlkZpwRWMuCyvPHCjRIbQT8uPAlASz1KZ5L7QTjmXLhgPCgv8gTQu1LOD6RrqpoLHfKTa0FA/7vhH0b6uWSHVyprRMcSrGJ4cCFlAdgxNuAq5pJuqzUxcFPBVVtQLPCj2J+kqOQpbSPrCrY4EieuXD0fnlspiYeuiv3QPln0FKsKHeLmcJ/LH4hHaK///5IMrFt4n+3r4UPKYOKLaQhxB8PVwli0sQttD9hVURpRbVDLyXFeEOTFCIRGZB8Z4hHjXKHkEvhGZRWXjl8vstdN8hZABYLP3E0H1DUedMpVCiSr70MNgas4PYW752mT7cSXEdfuOp1u4QB7G3qWwVsFxSxCngFgiMwbQzIZf4hqJ5W9CGpEyWSiWN4M8rH/Rkd3i3P7fG0FQuusGmi/6V5u1ZIltXtlaSUSVPu26z1GHIQRT5r2NhDv+6RvVyle3JVn5rTxcSIdN0Z22mYHgcJLigI4QNILdng6V/dEdIfs0XzOHvT/LXC25IsbhvFO/w/UtfASLeNlZc64xRLxMwuxd2b5O2uJ8xwuqWv2Xio=
