language: node_js
node_js:
- 11.1
- 10.15
- 8.9
git:
  depth: 3
script:
- npm run test
- npm run test:integration
after_success:
- npm run coverage
env:
  global:
  - secure: bHeanMiKVZB33yLIYKEDYeFTKThsVt0lCfCuWE69ZMWJV2kvy1GlrLhhTF/7bWqz3ygOGqmX5r51Ied2cOdc8NdLO4sWu/l+LTJF9P+2GhQfDHFCfLRHNHdsAbn/7gXsNSormy8zq9Zi8b+LCEfer3+JsIC4Vg4LHYNZj+QGF5pCj62sfBBHeLMZ0vGo294ug0n695dMCVRQNtd9B2jFtCayBbVBvlDvm1T1JxEssE0M4hAuzDBoP0OE/w/vXDKHOa1HiD0XSVLEdrEDQMv5wC7OiWMPChMYL0Hw25XanlxStDdPHrX8GRFMbfe/14aXRLVPTF0azLkkoLruOZ+LHWt2o7TBnuEGtQJEBFKbkCFe3w/E/SKCK/G867LjMld0ir6CNXME/gCIMB4I42tU4GkmL1wTEkFjlpYgPZFQBz4k7jEE0Ja50Grg4kXv91hPtBw5ottlI9Xr4yqSzE5int2RW2FRehaoAHleXZqIubxaW6P7rfc6n2zZuxCHSG7ptE8Ps7SZ2D+RbN7iIm7mmHjiwlmWUvvb7+rKMa6bwBo2nBksWuDiOinSl9gg+HKR+hPMDMNtK4PUJHihJta/KbK3qsHpuBfS00JkfDnD7aa4LycP29cjahsrHlbYk/pk4QUIfw7+QtPVeLzT6pfQeB1g/7CgO2v6oGWTcPFefcA=
  - secure: CdiA0A5cfKXJXIkPr5D0uvQFo0bxSI17fgFPBDz0rg+fw5DIy58wEhSmRT2/Z8wEwvxnhX7u+eP528KQ9hgM3ViKYGiyA5TBCcSicmBDKTB3C43mLWVBpo0lkiWT4xqJ8sJe3J+kaRCPULXZgYCyAZMsx8MZc5XFRJ7KV3zG+XzzPsajLaxXIAKIl9FpQw2Gep02wFKo/tOIP9EkniC18qMQw4/orWJURj/RcmLXa0fuI6aY3VcF5I5EGH6iBcc8ARV0bkPVJ3zAqwTj/+Vl44J+9ZSHw4CuMN2DvFDrJk9v2vA3UYTww/fIGwa2OGBXdt8+A44ZTPb/slty1GFJTsac0jv2iiFav6gYs3kFMh4hB4cHwkxkL6Ybm2trjanbZOm4oP65XR9ofHxZuL3YxFrFE1aOFSYwrs/cD3s7QzKAejjz6hxMPL4cynytGuLs7S5VCJUvCK8Inu+r5tBgtCYOTRDGYCi3KW45xt6CcT0P2ccqo8qh0+pJ6o/3BJPRY4Z8se8AfS4X32cvsqkJCRKkIL4edFO8Ri0vqmxWIsUFTp/yvwIXBNaidTj7cUWf1TVKIwO+LtIORwTwfLB6P2kYPT88hXG/Qg3iFzzQka1vbEY9nk2IwiyJvchfvMZZcZb8X+uLPc5ESVY8LocpxOWV7Z6EnjDkTU9VrTQfnBI=
